In [2]:
import numpy as np 
import pandas as pd

In [4]:
df=pd.read_excel(r'C:\Users\adisa\Downloads\Final scraped data.xlsx')

In [5]:
df.head(2)

restaurant_id               Name  Ratings  Price_for_one  \
0              0            Bakingo      4.3            300   
1              1  Empire Restaurant      4.1            300   

                                             cusines  \
0                                   Bakery, Desserts   
1  North Indian, Biryani, Kebab, Chinese, South I...   

                                     Restaurant_link  \
0  https: //www.zomato.com/bangalore/bakingo-vasa...   
1  https: //www.zomato.com/bangalore/empire-resta...   

                   location  Longitude   Latitute  delivery_review_number  
0  Vasanth Nagar, Bangalore  77.585169  12.988721                       0  
1   Shivajinagar, Bangalore  77.607542  12.986391                    4847

In [6]:
df['cusines'].replace(" ", '', regex=True, inplace=True)

In [7]:
new = df['cusines'].str.split(',', expand=True)

In [8]:
new

0           1         2           3            4        5  \
0         Bakery    Desserts      None        None         None     None   
1    NorthIndian     Biryani     Kebab     Chinese  SouthIndian  Mughlai   
2    NorthIndian     Biryani   Sichuan  StreetFood      Chinese     None   
3       IceCream      Bakery  Desserts        None         None     None   
4         Burger    FastFood      None        None         None     None   
..           ...         ...       ...         ...          ...      ...   
676       Bakery    Desserts      None        None         None     None   
677  NorthIndian       Rolls      None        None         None     None   
678       Mithai  StreetFood  FastFood        None         None     None   
679  NorthIndian        None      None        None         None     None   
680         Paan    Desserts      None        None         None     None   

             6     7  
0         None  None  
1    Beverages  None  
2         None  None  
3         None  None  
4         None  None  
..         ...   ...  
676       None  None  
677       None  None  
678       None  None  
679       None  None  
680       None  None  

[681 rows x 8 columns]

In [9]:
df['cusines'].nunique()

521

In [10]:
from keras.preprocessing.text import Tokenizer

In [11]:
t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(df['cusines'])
# summarize what was learned
dic = t.word_index

In [12]:
encoded_docs = t.texts_to_matrix(df['cusines'], mode='count')
print(encoded_docs)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
dic

{'northindian': 1,
 'chinese': 2,
 'beverages': 3,
 'desserts': 4,
 'biryani': 5,
 'southindian': 6,
 'fastfood': 7,
 'streetfood': 8,
 'mughlai': 9,
 'sichuan': 10,
 'shake': 11,
 'icecream': 12,
 'seafood': 13,
 'rolls': 14,
 'pizza': 15,
 'burger': 16,
 'bakery': 17,
 'kebab': 18,
 'andhra': 19,
 'sandwich': 20,
 'juices': 21,
 'momos': 22,
 'arabian': 23,
 'italian': 24,
 'kerala': 25,
 'mithai': 26,
 'asian': 27,
 'thai': 28,
 'continental': 29,
 'lebanese': 30,
 'hyderabadi': 31,
 'pasta': 32,
 'healthyfood': 33,
 'salad': 34,
 'wraps': 35,
 'cafe': 36,
 'bengali': 37,
 'mangalorean': 38,
 'mexican': 39,
 'waffle': 40,
 'japanese': 41,
 'bbq': 42,
 'tea': 43,
 'rajasthani': 44,
 'coffee': 45,
 'sushi': 46,
 'american': 47,
 'chettinad': 48,
 'oriental': 49,
 'tibetan': 50,
 'maharashtrian': 51,
 'vietnamese': 52,
 'korean': 53,
 'shawarma': 54,
 'odia': 55,
 'lucknowi': 56,
 'afghan': 57,
 'malaysian': 58,
 'barfood': 59,
 'indonesian': 60,
 'european': 61,
 'awadhi': 62,
 'paan'

In [14]:
new_dict = dict([(value, key) for key, value in dic.items()])
new_dict

{1: 'northindian',
 2: 'chinese',
 3: 'beverages',
 4: 'desserts',
 5: 'biryani',
 6: 'southindian',
 7: 'fastfood',
 8: 'streetfood',
 9: 'mughlai',
 10: 'sichuan',
 11: 'shake',
 12: 'icecream',
 13: 'seafood',
 14: 'rolls',
 15: 'pizza',
 16: 'burger',
 17: 'bakery',
 18: 'kebab',
 19: 'andhra',
 20: 'sandwich',
 21: 'juices',
 22: 'momos',
 23: 'arabian',
 24: 'italian',
 25: 'kerala',
 26: 'mithai',
 27: 'asian',
 28: 'thai',
 29: 'continental',
 30: 'lebanese',
 31: 'hyderabadi',
 32: 'pasta',
 33: 'healthyfood',
 34: 'salad',
 35: 'wraps',
 36: 'cafe',
 37: 'bengali',
 38: 'mangalorean',
 39: 'mexican',
 40: 'waffle',
 41: 'japanese',
 42: 'bbq',
 43: 'tea',
 44: 'rajasthani',
 45: 'coffee',
 46: 'sushi',
 47: 'american',
 48: 'chettinad',
 49: 'oriental',
 50: 'tibetan',
 51: 'maharashtrian',
 52: 'vietnamese',
 53: 'korean',
 54: 'shawarma',
 55: 'odia',
 56: 'lucknowi',
 57: 'afghan',
 58: 'malaysian',
 59: 'barfood',
 60: 'indonesian',
 61: 'european',
 62: 'awadhi',
 63: 'p

In [15]:
df1 = pd.DataFrame(encoded_docs)
df1

0    1    2    3    4    5    6    7    8    9   ...   66   67   68  \
0    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
2    0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
676  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
677  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
678  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  ...  0.0  0.0  0.0   
679  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
680  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      69   70   71   72   73   74   75  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
676  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
677  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
678  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
679  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
680  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[681 rows x 76 columns]

In [16]:
df1.rename(columns ={1: 'northindian',
 2: 'chinese',
 3: 'beverages',
 4: 'desserts',
 5: 'biryani',
 6: 'southindian',
 7: 'fastfood',
 8: 'streetfood',
 9: 'mughlai',
 10: 'sichuan',
 11: 'shake',
 12: 'icecream',
 13: 'seafood',
 14: 'rolls',
 15: 'pizza',
 16: 'burger',
 17: 'bakery',
 18: 'kebab',
 19: 'andhra',
 20: 'sandwich',
 21: 'juices',
 22: 'momos',
 23: 'arabian',
 24: 'italian',
 25: 'kerala',
 26: 'mithai',
 27: 'asian',
 28: 'thai',
 29: 'continental',
 30: 'lebanese',
 31: 'hyderabadi',
 32: 'pasta',
 33: 'healthyfood',
 34: 'salad',
 35: 'wraps',
 36: 'cafe',
 37: 'bengali',
 38: 'mangalorean',
 39: 'mexican',
 40: 'waffle',
 41: 'japanese',
 42: 'bbq',
 43: 'tea',
 44: 'rajasthani',
 45: 'coffee',
 46: 'sushi',
 47: 'american',
 48: 'chettinad',
 49: 'oriental',
 50: 'tibetan',
 51: 'maharashtrian',
 52: 'vietnamese',
 53: 'korean',
 54: 'shawarma',
 55: 'odia',
 56: 'lucknowi',
 57: 'afghan',
 58: 'malaysian',
 59: 'barfood',
 60: 'indonesian',
 61: 'european',
 62: 'awadhi',
 63: 'paan',
 64: 'pancake',
 65: 'modernindian',
 66: 'burmese',
 67: 'gujarati',
 68: 'fingerfood',
 69: 'french',
 70: 'panini',
 71: 'middleeastern',
 72: 'portuguese',
 73: 'parsi',
 74: 'singaporean',
 75: 'mishti'},inplace=True)

In [17]:
df1.drop(0,axis=1,inplace=True)

In [18]:
df2 = df.join(df1)
df2

restaurant_id                                           Name  Ratings  \
0                0                                        Bakingo      4.3   
1                1                              Empire Restaurant      4.1   
2                2                               Flavors Of North      3.8   
3                3                                          ibaco      4.5   
4                4                                     McDonald's      4.0   
..             ...                                            ...      ...   
676            676                 Sweet Bake - Cake And Desserts      0.0   
677            677                                      Rosy Roti      4.1   
678            678                         Svadu Pure Ghee Sweets      3.4   
679            679                               Uncle Tom's Cafe      3.6   
680            680  The Betel Leaf Co - Originally from Bangalore      4.4   

     Price_for_one                                            cusines  \
0              300                                    Bakery,Desserts   
1              300  NorthIndian,Biryani,Kebab,Chinese,SouthIndian,...   
2              300     NorthIndian,Biryani,Sichuan,StreetFood,Chinese   
3              300                           IceCream,Bakery,Desserts   
4              300                                    Burger,FastFood   
..             ...                                                ...   
676            250                                    Bakery,Desserts   
677            250                                  NorthIndian,Rolls   
678            250                         Mithai,StreetFood,FastFood   
679            250                                        NorthIndian   
680            250                                      Paan,Desserts   

                                       Restaurant_link  \
0    https: //www.zomato.com/bangalore/bakingo-vasa...   
1    https: //www.zomato.com/bangalore/empire-resta...   
2    https: //www.zomato.com/bangalore/flavors-of-n...   
3    https: //www.zomato.com/bangalore/ibaco-brigad...   
4    https: //www.zomato.com/bangalore/mcdonalds-mg...   
..                                                 ...   
676  https: //www.zomato.com/bangalore/sweet-bake-c...   
677  https: //www.zomato.com/bangalore/rosy-roti-do...   
678  https: //www.zomato.com/bangalore/svadu-pure-g...   
679  https: //www.zomato.com/bangalore/uncle-toms-c...   
680  https: //www.zomato.com/bangalore/the-betel-le...   

                             location  Longitude   Latitute  \
0            Vasanth Nagar, Bangalore  77.585169  12.988721   
1             Shivajinagar, Bangalore  77.607542  12.986391   
2              Rajajinagar, Bangalore  77.554883  12.988234   
3             Brigade Road, Bangalore  77.606966  12.971485   
4                  MG Road, Bangalore  77.606790  12.975526   
..                                ...        ...        ...   
676  Koramangala 7th Block, Bangalore  77.613478  12.936485   
677                 Domlur, Bangalore  77.638196  12.962467   
678                    BTM, Bangalore  77.604565  12.911276   
679     Basaveshwara Nagar, Bangalore  77.539475  12.993161   
680          Seshadripuram, Bangalore  77.575342  12.993188   

     delivery_review_number  ...  burmese  gujarati  fingerfood  french  \
0                         0  ...      0.0       0.0         0.0     0.0   
1                      4847  ...      0.0       0.0         0.0     0.0   
2                         2  ...      0.0       0.0         0.0     0.0   
3                       107  ...      0.0       0.0         0.0     0.0   
4                       212  ...      0.0       0.0         0.0     0.0   
..                      ...  ...      ...       ...         ...     ...   
676                       0  ...      0.0       0.0         0.0     0.0   
677                       0  ...      0.0       0.0         0.0     0.0   
678                       0  ...      0.0       0.0         0.

In [19]:
df2.drop(columns = ['restaurant_id','Name','Longitude','Latitute','Restaurant_link','cusines','delivery_review_number'],inplace= True)

In [20]:
df2

Ratings  Price_for_one                          location  northindian  \
0        4.3            300          Vasanth Nagar, Bangalore          0.0   
1        4.1            300           Shivajinagar, Bangalore          1.0   
2        3.8            300            Rajajinagar, Bangalore          1.0   
3        4.5            300           Brigade Road, Bangalore          0.0   
4        4.0            300                MG Road, Bangalore          0.0   
..       ...            ...                               ...          ...   
676      0.0            250  Koramangala 7th Block, Bangalore          0.0   
677      4.1            250                 Domlur, Bangalore          1.0   
678      3.4            250                    BTM, Bangalore          0.0   
679      3.6            250     Basaveshwara Nagar, Bangalore          1.0   
680      4.4            250          Seshadripuram, Bangalore          0.0   

     chinese  beverages  desserts  biryani  southindian  fastfood  ...  \
0        0.0        0.0       1.0      0.0          0.0       0.0  ...   
1        1.0        1.0       0.0      1.0          1.0       0.0  ...   
2        1.0        0.0       0.0      1.0          0.0       0.0  ...   
3        0.0        0.0       1.0      0.0          0.0       0.0  ...   
4        0.0        0.0       0.0      0.0          0.0       1.0  ...   
..       ...        ...       ...      ...          ...       ...  ...   
676      0.0        0.0       1.0      0.0          0.0       0.0  ...   
677      0.0        0.0       0.0      0.0          0.0       0.0  ...   
678      0.0        0.0       0.0      0.0          0.0       1.0  ...   
679      0.0        0.0       0.0      0.0          0.0       0.0  ...   
680      0.0        0.0       1.0      0.0          0.0       0.0  ...   

     burmese  gujarati  fingerfood  french  panini  middleeastern  portuguese  \
0        0.0       0.0         0.0     0.0     0.0            0.0         0.0   
1        0.0       0.0         0.0     0.0     0.0            0.0         0.0   
2        0.0       0.0         0.0     0.0     0.0            0.0         0.0   
3        0.0       0.0         0.0     0.0     0.0            0.0         0.0   
4        0.0       0.0         0.0     0.0     0.0            0.0         0.0   
..       ...       ...         ...     ...     ...            ...         ...   
676      0.0       0.0         0.0     0.0     0.0            0.0         0.0   
677      0.0       0.0         0.0     0.0     0.0            0.0         0.0   
678      0.0       0.0         0.0     0.0     0.0            0.0         0.0   
679      0.0       0.0         0.0     0.0     0.0            0.0         0.0   
680      0.0       0.0         0.0     0.0     0.0            0.0         0.0   

     parsi  singaporean  mishti  
0      0.0          0.0     0.0  
1      0.0          0.0     0.0  
2      0.0          0.0     0.0  
3      0.0          0.0     0.0  
4      0.0          0.0     0.0  
..     ...          ...     ...  
676    0.0          0.0     0.0  
677    0.0          0.0     0.0  
678    0.0          0.0     0.0  
679    0.0          0.0     0.0  
680    0.0          0.0     0.0  

[681 rows x 78 columns]

In [21]:
df2.drop(columns = ['Ratings'], inplace= True)

In [22]:
pt=df2.set_index('location')

In [23]:
pt

Price_for_one  northindian  chinese  \
location                                                                
Vasanth Nagar, Bangalore                    300          0.0      0.0   
Shivajinagar, Bangalore                     300          1.0      1.0   
Rajajinagar, Bangalore                      300          1.0      1.0   
Brigade Road, Bangalore                     300          0.0      0.0   
MG Road, Bangalore                          300          0.0      0.0   
...                                         ...          ...      ...   
Koramangala 7th Block, Bangalore            250          0.0      0.0   
Domlur, Bangalore                           250          1.0      0.0   
BTM, Bangalore                              250          0.0      0.0   
Basaveshwara Nagar, Bangalore               250          1.0      0.0   
Seshadripuram, Bangalore                    250          0.0      0.0   

                                  beverages  desserts  biryani  southindian  \
location                                                                      
Vasanth Nagar, Bangalore                0.0       1.0      0.0          0.0   
Shivajinagar, Bangalore                 1.0       0.0      1.0          1.0   
Rajajinagar, Bangalore                  0.0       0.0      1.0          0.0   
Brigade Road, Bangalore                 0.0       1.0      0.0          0.0   
MG Road, Bangalore                      0.0       0.0      0.0          0.0   
...                                     ...       ...      ...          ...   
Koramangala 7th Block, Bangalore        0.0       1.0      0.0          0.0   
Domlur, Bangalore                       0.0       0.0      0.0          0.0   
BTM, Bangalore                          0.0       0.0      0.0          0.0   
Basaveshwara Nagar, Bangalore           0.0       0.0      0.0          0.0   
Seshadripuram, Bangalore                0.0       1.0      0.0          0.0   

                                  fastfood  streetfood  mughlai  ...  burmese  \
location                                                         ...            
Vasanth Nagar, Bangalore               0.0         0.0      0.0  ...      0.0   
Shivajinagar, Bangalore                0.0         0.0      1.0  ...      0.0   
Rajajinagar, Bangalore                 0.0         1.0      0.0  ...      0.0   
Brigade Road, Bangalore                0.0         0.0      0.0  ...      0.0   
MG Road, Bangalore                     1.0         0.0      0.0  ...      0.0   
...                                    ...         ...      ...  ...      ...   
Koramangala 7th Block, Bangalore       0.0         0.0      0.0  ...      0.0   
Domlur, Bangalore                      0.0         0.0      0.0  ...      0.0   
BTM, Bangalore                         1.0         1.0      0.0  ...      0.0   
Basaveshwara Nagar, Bangalore          0.0         0.0      0.0  ...      0.0   
Seshadripuram, Bangalore               0.0         0.0      0.0  ...      0.0   

                                  gujarati  fingerfood  french  panini  \
location                                                                 
Vasanth Nagar, Bangalore               0.0         0.0     0.0     0.0   
Shivajinagar, Bangalore                0.0         0.0     0.0     0.0   
Rajajinagar, Bangalore                 0.0         0.0     0.0     0.0   
Brigade Road, Bangalore                0.0         0.0     0.0     0.0   
MG Road, Bangalore                     0.0         0.0     0.0     0.0   
...                                    ...         ...     ...     ...   
Koramangala 7th Block, Bangalore       0.0         0.0     0.0     0.0   
Domlur, Bangalore                      0.0         0.0     0.0     0.0   
BTM, Bangalore                         0.0         0.0     0.0     0.0   
Basaveshwara Nagar, Bangalore          0.0         0.0     0.0     0.0   
Seshadripuram, Bangalore               0.0         0.0     0.0     0.0   

                                  middl

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity_scores = cosine_similarity(pt)

In [26]:
similarity_scores

array([[1.        , 0.99995   , 0.99996111, ..., 0.99996489, 0.99998089,
        0.99998622],
       [0.99995   , 1.        , 0.99996667, ..., 0.99993712, 0.99996645,
        0.99994511],
       [0.99996111, 0.99996667, 1.        , ..., 0.99996156, 0.99997756,
        0.99995622],
       ...,
       [0.99996489, 0.99993712, 0.99996156, ..., 1.        , 0.999968  ,
        0.99996   ],
       [0.99998089, 0.99996645, 0.99997756, ..., 0.999968  , 1.        ,
        0.999976  ],
       [0.99998622, 0.99994511, 0.99995622, ..., 0.99996   , 0.999976  ,
        1.        ]])

In [27]:
def recommend(location_name):
    index=np.where(pt.index==location_name)[0][0]
    similar_location=sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:2]
    for i in similar_location:
        print(pt.index[i[0]])

In [28]:
recommend('Seshadripuram, Bangalore')

Jayanagar, Bangalore


In [29]:
sorted(list(enumerate(similarity_scores[0])),key=lambda x:x[1],reverse=True)

[(0, 1.0),
 (401, 1.0),
 (334, 0.9999995555795547),
 (432, 0.9999995555795547),
 (499, 0.9999995555795547),
 (673, 0.9999995555795547),
 (676, 0.9999995555795547),
 (242, 0.9999993055794265),
 (247, 0.9999993055794265),
 (272, 0.9999972224189707),
 (356, 0.9999972224189707),
 (610, 0.9999972224189707),
 (3, 0.9999944446141922),
 (57, 0.9999944446141922),
 (671, 0.9999942223374793),
 (246, 0.9999940973381416),
 (477, 0.9999915559350943),
 (487, 0.9999915559350943),
 (490, 0.9999915559350943),
 (319, 0.9999915557084417),
 (320, 0.9999915557084417),
 (244, 0.9999909723907665),
 (245, 0.9999899308349531),
 (315, 0.9999895557473297),
 (144, 0.9999888900616264),
 (219, 0.9999888900616264),
 (226, 0.9999888900616264),
 (229, 0.9999888900616264),
 (234, 0.9999888900616264),
 (235, 0.9999888900616264),
 (275, 0.9999888893209706),
 (278, 0.9999888893209706),
 (397, 0.9999888891357971),
 (311, 0.9999868891022925),
 (317, 0.9999868891022925),
 (680, 0.9999862226076929),
 (310, 0.9999855558611047),

In [30]:
df2 = df2.iloc[:,0:52]

In [31]:
df2['location'].value_counts()
df2['location'].value_counts().loc[lambda x : x>5]
df3 = df2[df2['location'].map(df2['location'].value_counts()) > 5]
df3['location'].nunique()

36

In [32]:
df3.shape

(605, 52)

In [33]:
df3['location'] = df3['location'].str.replace(', Bangalore', '')

C:\Users\adisa\AppData\Local\Temp\ipykernel_2684\2921896998.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['location'] = df3['location'].str.replace(', Bangalore', '')


In [34]:
col =['location']
for i in col:
    F=pd.get_dummies(df3[i]) 
    df3 = pd.concat([df3,F],axis=1)
    df3.drop(i,inplace = True, axis = 1)

In [115]:
df3.iloc[:,:].columns

Index(['Price_for_one', 'northindian', 'chinese', 'beverages', 'desserts',
       'biryani', 'southindian', 'fastfood', 'streetfood', 'mughlai',
       'sichuan', 'shake', 'icecream', 'seafood', 'rolls', 'pizza', 'burger',
       'bakery', 'kebab', 'andhra', 'sandwich', 'juices', 'momos', 'arabian',
       'italian', 'kerala', 'mithai', 'asian', 'thai', 'continental',
       'lebanese', 'hyderabadi', 'pasta', 'healthyfood', 'salad', 'wraps',
       'cafe', 'bengali', 'mangalorean', 'mexican', 'waffle', 'japanese',
       'bbq', 'tea', 'rajasthani', 'coffee', 'sushi', 'american', 'chettinad',
       'oriental', 'tibetan', 'BTM', 'Banashankari', 'Basavanagudi',
       'Basaveshwara Nagar', 'Brigade Road', 'Church Street',
       'Cunningham Road', 'Domlur', 'Frazer Town', 'HBR Layout', 'Indiranagar',
       'Jayanagar', 'Jeevan Bhima Nagar', 'Kammanahalli',
       'Koramangala 5th Block', 'Koramangala 6th Block',
       'Koramangala 7th Block', 'Koramangala 8th Block', 'Lavelle Road',
  

In [35]:
X=df3.drop(['Price_for_one'],axis=1) 
Y = df3['Price_for_one']

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [37]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.25,random_state=4)

In [38]:
X_train

northindian  chinese  beverages  desserts  biryani  southindian  \
232          0.0      1.0        0.0       0.0      0.0          0.0   
540          0.0      0.0        0.0       0.0      0.0          0.0   
68           1.0      0.0        0.0       1.0      1.0          0.0   
278          0.0      0.0        0.0       0.0      0.0          0.0   
163          0.0      0.0        0.0       0.0      0.0          1.0   
..           ...      ...        ...       ...      ...          ...   
675          0.0      0.0        1.0       1.0      0.0          0.0   
413          0.0      0.0        0.0       1.0      0.0          0.0   
501          0.0      0.0        0.0       1.0      0.0          0.0   
193          0.0      0.0        0.0       0.0      0.0          0.0   
134          0.0      0.0        0.0       1.0      0.0          0.0   

     fastfood  streetfood  mughlai  sichuan  ...  Richmond Road  \
232       0.0         0.0      0.0      0.0  ...              0   
540       0.0         0.0      0.0      0.0  ...              0   
68        0.0         0.0      1.0      0.0  ...              0   
278       0.0         0.0      0.0      0.0  ...              0   
163       0.0         0.0      0.0      0.0  ...              0   
..        ...         ...      ...      ...  ...            ...   
675       0.0         0.0      0.0      0.0  ...              0   
413       0.0         0.0      0.0      0.0  ...              0   
501       0.0         0.0      0.0      0.0  ...              0   
193       1.0         0.0      0.0      0.0  ...              0   
134       1.0         0.0      0.0      0.0  ...              0   

     Seshadripuram  Shanti Nagar  Shivajinagar  St. Marks Road  Thippasandra  \
232              0             0             0               0             0   
540              0             0             0               0             0   
68               0             0             0               0             1   
278              1             0             0               0             0   
163              0             0             0               0             0   
..             ...           ...           ...             ...           ...   
675              0             0             0               0             0   
413              0             0             0               0             0   
501              0             0             0               0             0   
193              0             0             0               0             0   
134              0             0             0               0             0   

     Ulsoor  Vasanth Nagar  Vijay Nagar  Wilson Garden  
232       0              0            0              0  
540       0              0            0              0  
68        0              0            0              0  
278       0              0            0              0  
163       0              0            0              0  
..      ...            ...          ...            ...  
675       0              0            0              0  
413       0              0            0              0  
501       0              0            0              0  
193       0              0            0              0  
134       0              0            0              0  

[453 rows x 86 columns]

In [39]:
X_test.shape

(152, 86)

In [40]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler() 

In [41]:
X_train=sc.fit_transform(X_train)

In [42]:
X_train 

array([[-0.8772293 ,  1.15544431, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [ 1.1399528 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       ...,
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584]])

In [43]:
X_test=sc.transform(X_test) 

In [44]:
from sklearn.linear_model import LinearRegression 

In [45]:
reg=LinearRegression() 

In [46]:
reg.fit(X_train,Y_train) 

LinearRegression()

In [47]:
Y_pred=reg.predict(X_test)

In [48]:
from sklearn import metrics 

In [49]:
R2=metrics.r2_score(Y_test, Y_pred) 
R2 

-0.27422510178804393

In [50]:
MSE=metrics.mean_squared_error(Y_test, Y_pred) 
MSE 

9288.513074809032

In [51]:
RMSE=np.sqrt(MSE) 
RMSE 

96.37693227535847

In [52]:
cusins=['northindian', 'chinese', 'beverages', 'desserts',
       'biryani', 'southindian', 'fastfood', 'streetfood', 'mughlai',
       'sichuan', 'shake', 'icecream', 'seafood', 'rolls', 'pizza', 'burger',
       'bakery', 'kebab', 'andhra', 'sandwich', 'juices', 'momos', 'arabian',
       'italian', 'kerala', 'mithai', 'asian', 'thai', 'continental',
       'lebanese', 'hyderabadi', 'pasta', 'healthyfood', 'salad', 'wraps',
       'cafe', 'bengali', 'mangalorean', 'mexican', 'waffle', 'japanese',
       'bbq', 'tea', 'rajasthani', 'coffee', 'sushi', 'american', 'chettinad',
       'oriental', 'tibetan']
location=['BTM', 'Banashankari', 'Basavanagudi', 'Basaveshwara Nagar',
       'Brigade Road', 'Church Street', 'Cunningham Road', 'Domlur',
       'Frazer Town', 'HBR Layout', 'Indiranagar', 'Jayanagar',
       'Jeevan Bhima Nagar', 'Kammanahalli', 'Koramangala 5th Block',
       'Koramangala 6th Block', 'Koramangala 7th Block',
       'Koramangala 8th Block', 'Lavelle Road', 'MG Road', 'Majestic',
       'Malleshwaram', 'Old Airport Road', 'RT Nagar', 'Rajajinagar',
       'Residency Road', 'Richmond Road', 'Seshadripuram', 'Shanti Nagar',
       'Shivajinagar', 'St. Marks Road', 'Thippasandra', 'Ulsoor',
       'Vasanth Nagar', 'Vijay Nagar', 'Wilson Garden']
final=cusins+location

In [55]:
cu1 ='northindian'.lower().replace(' ','')
cu2 = ''.lower().replace(' ','')
cu3 =''.lower().replace(' ','')
cu4 = ''.lower().replace(' ','')
cu5 = ''.lower().replace(' ','')

# North Indian, Continental, BBQ, Desserts, Beverages
# Mexican, Tex-Mex, Beverages
# Italian, Fast Food, Pasta, Pizza, Beverages, Desserts
count = 0
locat = 'whitefield'.title()
L = []
for i in final:
    if (cu1 == i) or (locat == i) or (cu2 == i) or (cu3==i)  or (cu4 == i) or (cu5 == i ):
        L.append(1)
        count += 1
    else:
        L.append(0)

L=[L]
A = sc.transform(L)
print(count)
if count == 0:
    print('error')
else:
    num = reg.predict(L)[0]
    print(int(round(num)))

1
192


C:\Users\adisa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
